mozhengfly:
  storage:
    aliyun:
      enable: true
      end-point:
      access-key-id:
      access-key-secret:
      bucket:
      remote-directory:

logging:
  level:
    root: info
    com.mozhengfly.boot: debug
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${datasource.host}/mo?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: ${datasource.username}
    password: ${datasource.password}
  redis:
    host: ENC(pLTFbS+pEFIIHeg/JkbdJHJif5kpjcFC)
    port: ENC(sel8QPrsaaQTVe1W8uxYIw==)
    password: ENC(czZ/wwCm6hHbuVGEzBC7rnk6l2HwNGYg)
    redisson:
#      file: classpath:redisson.yml
      config:
        singleServerConfig:
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          password: ${spring.redis.password}
          subscriptionsPerConnection: 5
          clientName: "redisson-demo"
          address: "redis://${spring.redis.host}:${spring.redis.port}"
          subscriptionConnectionMinimumIdleSize: 1
          subscriptionConnectionPoolSize: 50
          connectionMinimumIdleSize: 32
          connectionPoolSize: 64
          database: 8


