mozhengfly:
  storage:
    aliyun:
      enable: true
      end-point:
      access-key-id:
      access-key-secret:
      bucket:
      remote-directory:

logging:
  level:
    root: info
    com.mozhengfly.boot: debug
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${datasource.host}/practice?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: ${datasource.username}
    password: ${datasource.password}
